name: Build

on:
  push:
    branches: 
    - main
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"

    - name: Install XK6
      run:  go install go.k6.io/xk6/cmd/xk6@latest

    - name: Test
      run: make test